#spring的配置，jsp前后缀配置，数据源配置本系统采用读写分离所以有几个数据源来引用
spring:
  mvc:
    view:
      prefix : /WEB-INF/views/
      suffix : .jsp
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/rainbowman
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.102.56:3306/test
      username: pig
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.102.36:3306/test
      username: pig
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
#服务端口配置
server:
  port: 8888
mybatis:
  type:
    alias:
      package: com.rainbowman.miniprogram.server.bean
#log日志路径，springboot 默认 sl4j+LogBack以及日志级别配置
logging:
  file: D:/test/wxdemo.log
  level:
    root: info
    com.rainbowman.miniprogram.server.mapper: debug


